04 auth
idrahoner/goit-nodejs-hw pull request #4
Opened 2023-02-17 09:32 UTC by idrahoner

2023-02-17 21:04 UTC, Eastvarga requested changes
Є зауваження

2023-02-17 21:04 UTC, Eastvarga commented on middlewares/check-auth-user.js
> +    console.log('   Authorization:    ', authorization);
консолі у робочому коді не потрібні

2023-02-17 21:04 UTC, Eastvarga commented on middlewares/check-auth-user.js
> +    req.ownerId = userId;
це зайве, у вас вже є юзер, потрібно його використовувати (деструктивне присвоєння з перейменуванням змінної повинно вирішити все)

2023-02-17 21:04 UTC, Eastvarga commented on routes/api/contacts.js
> +router.use(checkAuthUser);
checkAuthUser - дуже незрозуміле ім'я
Auth \ AuthMidlware - так зрозуміліше що це мідлвар авторизації

2023-02-17 21:04 UTC, Eastvarga commented on services/contacts-service.js
> +  validateId(id);
Валідувати айді краще на рівні мідлвару ще до контроллера після мідлвару авторізації

2023-02-18 13:47 UTC, idrahoner commented on middlewares/check-auth-user.js
> +    console.log('   Authorization:    ', authorization);
✅

2023-02-18 13:47 UTC, idrahoner commented on middlewares/check-auth-user.js
> +    req.ownerId = userId;
✅

2023-02-18 13:47 UTC, idrahoner commented on services/contacts-service.js
> +  validateId(id);
✅

2023-02-18 13:47 UTC, idrahoner commented on routes/api/contacts.js
> +router.use(checkAuthUser);
✅

2023-02-19 11:50 UTC, NadyaHristuk approved these changes

2023-02-19 11:50 UTC, merged